# Generated by Django 4.2.1 on 2023-05-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
