# Generated by Django 4.2.1 on 2023-06-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("msg", models.CharField(max_length=100)),
                ("assignee", models.CharField(blank=True, max_length=100)),
                ("e_mail", models.EmailField(blank=True, max_length=254)),
                (
                    "user_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.myuser",
                    ),
                ),
            ],
        ),
    ]
