# Generated by Django 4.2.1 on 2023-06-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0002_remove_myuser_name_remove_myuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="my_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="myuser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
