# Generated by Django 4.2.1 on 2023-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0003_rename_user_myuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="assignee",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="note",
            name="e_mail",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="note",
            name="msg",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=20),
        ),
    ]
